import numpy

                                                ##Solutions to Euler's Problems##
                                                
"""1 - If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
Find the sum of all the multiples of 3 or 5 below 1000."""
total=0
for i in range(1000):
    if i%3 == 0 or i%5 == 0:
        total=total+i
print(total)

"""2 - Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."""
total = 0
firstvalue = 1
secondvalue = 1
sum = 0

while sum <= 4000000:
    if sum % 2 == 0:
        total += sum
    firstvalue = secondvalue
    secondvalue = sum
    sum = firstvalue + secondvalue

print(total)

"""3 - The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?"""
largenumber = 112123123412345
iteration = 2
while iteration * iteration < largenumber:
    while largenumber % iteration == 0:
        largenumber = largenumber / iteration
    iteration = iteration + 1

print(largenumber)

"""4. A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.

Find the largest palindrome made from the product of two 3-digit numbers."""
#sequencename[::-1] to reverse a sequence
def reverse(string):
    return string[::-1]

def palindrome(string):
    string=str(string)
    list=[]
    for character in string:
        list.append(character)
    if len(string)%2==0 and len(string) != 0:
        indexposition=int(len(string)/2)
        if list[:indexposition]==reverse(list[indexposition:]):
            return True
    elif len(string)%2!=0 or len(string) == 0:
        return False
#Works as a palindrome boolean

#Have to make a reverse and palindrome function boolean first
firstlist=[]
secondlist=[]
products=[]
palindromes=[]
first=999
second=999
largest=first*second

while first!=100:
    firstlist.append(first)
    first-=1
while second!=100:
    secondlist.append(second)
    second-=1

for i in firstlist:
    for j in secondlist:
        result=i*j
        products.append(result)
for product in products:
    if palindrome(product)==True:
        palindromes.append(product)

print(max(palindromes))


"""5. 2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?"""
from math import lcm

print(lcm(*range(1, 21)))
#Answer is 232792560, done with python version 3.10 on IDLE

#list=[]
#possibility_list=[]
#base=1
#numberlist=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
#for number in numberlist:
#    for iteration in range(500): 
#        list.append(iteration*number)
#for possibility in list:
#    if list.count(possibility)==20:
#        print("Found LCM of [1:21] -->", str(possibility))
#        possibility_list.append(possibility)
#print(max(possibility_list))
#Former Tried Solution, found an easier method through python manual


"""6. Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum."""
total=0
sum=0
for number in range(1, 101):
    number**=2
    total+=number
    #This is the sum of the squares of the numbers
for number2 in range(1,101):
    sum+=number2
sum**=2 #square of the sum
print(abs(total-sum))
